name = "Susty Hugo"
license = "MIT"
licenselink = "https://github.com/kampfq/susty/blob/master/LICENSE"
description = "Building for sustainability with Hugo."
homepage = "https://github.com/kampfq/susty/"
tags = ["blog", "plain", "sustainability", "green", "eco"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Kampfq"
  homepage = "https://github.com/kampfq"
